n = map(int, input('Введите количество элементов первого набора: ').split())
m = map(int, input('Введите количество элементов второго набора: ').split())
a = set(map(int, input('введите элементы певрого набора: ').split()))
b = set(map(int, input('Введите элементы второго набора: ').split()))
print(*sorted(a & b))